### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by dannyfritz** [whediger/mypage#1]
Hey Wes!

Interesting take on the world changing. :rocket: 

```
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
```

Did you happen to get this loop from Look Around You? https://youtu.be/FBaVwwuErmU?t=86

Look forward to see you in class! (I remember you from g18 hiring day!)

**Comment by whediger** [comment]
Thank you!
